[package]
name = "nix_parser"
version = "0.1.0"
authors = ["Simon Vandel Sillesen <simon.vandel@gmail.com>"]
repository = "https://github.com/simonvandel/nix_parser"

[dependencies]
nom = "^1.2.4"
itertools = "0.4.16"

[dev-dependencies]
clap = "2"